version: '3'

services:
    frontend:
        build: ./frontend/webserver/
        ports: 
            - 80:80
        volumes:
            - /app/node_modules
    backend:
        build: ./backend/
        ports: 
            - 8080:8080
            - 50051:50051
        links:
            - database
        depends_on: 
            - database
    database:
        build: ./database
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=fitnesscenter  
            - POSTGRES_PASSWORD=1234
            - POSTGRES_USER=postgres
