# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'sinatra'
gem 'grpc'
gem 'grpc-tools'
gem 'multi_json'
gem 'pg'
gem 'rack'
gem 'rack-protection'
gem 'rack-cors'
group :test do
    gem 'json-schema'
    gem "rspec"
    gem "rack-test"
 end
