# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route_fitness_center.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "routeguide.Date" do
    optional :day, :int32, 1
    optional :month, :int32, 2
    optional :year, :int32, 3
    optional :hour, :int32, 4
    optional :minutes, :int32, 5
  end
  add_message "routeguide.TrainingPlanRequest" do
    optional :member_id, :string, 1
    optional :date, :message, 2, "routeguide.Date"
  end
  add_message "routeguide.AppointmentRequest" do
    optional :member_id, :string, 1
    optional :date, :message, 2, "routeguide.Date"
    optional :note, :string, 3
  end
  add_message "routeguide.Confirmation" do
    optional :code, :int32, 1
    optional :description, :string, 2
  end
end

module Routeguide
  Date = Google::Protobuf::DescriptorPool.generated_pool.lookup("routeguide.Date").msgclass
  TrainingPlanRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("routeguide.TrainingPlanRequest").msgclass
  AppointmentRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("routeguide.AppointmentRequest").msgclass
  Confirmation = Google::Protobuf::DescriptorPool.generated_pool.lookup("routeguide.Confirmation").msgclass
end
